### ISSUE TITLE
Passing requiers field as an input to another resolver

### ISSUE THREAD

**Issue by nirsagi** [preply/graphene-federation#30]
Hey lets say i have 2 services
the first class looks like
```
@key(fields="id")
@key(fields="flowId")
class SubscriptionManager(graphene.ObjectType):
    id = graphene.String(required=True)
    flow_id = graphene.String()

    @staticmethod
    def resolve_flow_id(parent, info):
        return "ABC-123"
```

the in the second service i want to be able to pass the flow_id as an input to another resolver
```
@extend(fields="id")
class SubscriptionManager(graphene.ObjectType):
    id = external(graphene.String(required=True))
    flow_id = external(graphene.String())
    get_alot_of_params = requires(graphene.String(), fields="flowId")
```
i would like that get_alot_of_params will receive flow_id from the first service but also other params passed from the parent. is there a way to do it?

**Comment by makskant** [comment]
Hey, we are having a similar problem. Do you have any updates on that?

**Comment by chinskiy** [comment]
Hello @nirsagi  ,

This repository is going to be archived

Further development of graphene-federation will be at https://github.com/graphql-python/graphene-federation
Please address your further pull requests and issues there

Best regards
