### ISSUE TITLE
Congrats on the work

### ISSUE THREAD

**Issue by syrusakbary** [preply/graphene-federation#34]
Hi everyone,

I'm Syrus, creator of Graphene :). Great work on this package.
I would love to have the project under the umbrella of the `graphql-python` organization.

Let me know if you would be interested in forming part of the organization!

**Comment by grillorafael** [comment]
Just adding a support comment to say that I do think that moving this package under the `graphql-python` umbrella would be very positive.

**Comment by syrusakbary** [comment]
cc / @erebus1

**Comment by tcleonard** [comment]
That would be great to have that either under the `graphql-python` organization or even incorporated in `graphene` eventually!

**Comment by chinskiy** [comment]
Hello folks ,

This repository is going to be archived

Further development of graphene-federation will be at https://github.com/graphql-python/graphene-federation
Please address your further pull requests and issues there

Best regards

**Comment by tcleonard** [comment]
@chinskiy we would need to publish on Pypi from the https://github.com/graphql-python/graphene-federation so that it can truly become "the official" maintained version.
I haven't looked into it yet but I assume I won't have the necessary permissions to change it to point to the new repo. Could we sync on that topic? Maybe the graphene slack space: https://graphenetools.slack.com/ ?

**Comment by chinskiy** [comment]
@tcleonard we've provided `Owner` permissions for PyPi to the https://pypi.org/user/erikwrede/ user (@ erikwrede I suppose) who is also a part of `graphql-python`
As it's a full transfer feel free to remove our team users from PyPi

If there would be a need for additional help from our side in terms of transferring permissions feel free to write me at chinskiy@preply.com or just send an invite to this Slack space(seems like there is a domain restriction for signup)
