### ISSUE TITLE
Federated services Database design

### ISSUE THREAD

**Issue by cyril36** [preply/graphene-federation#35]
Hi,
It is not an issue but a question about the way of working.

I would like to be sure how should be designed the databases of different Federated services that will communicate to each other.

We have 2 graphql services and 2 different databases :

- user
- post

User service will contain a database with the following table

```
user table contains:
- Id
- email
- password
```

Post service will contain a database with the following table

```
Post table contains :
- id_post
- title
- description
- id_user
```
In Django : 
User Model :
```
class User(models.Model):
    email = models.EmailField(_('email address'), unique=True)
    password = models.CharField(max_length=100)
```
Post Model : 
```
class Post(models.Model):
	title = models.CharField(max_length=100)
	description = models.CharField(max_length=100)
	id_user = models.IntegerField()    
         // this field will get the id of the user from the other service
```

In graphql we would have

User service:

```
Type user key(fields=Id) {
     Id: int
     Email:string
     Password : string
}
```

Post service

```
Type post key(fields=Id) {
     Id: int
     Title : string
     Description : string
     user_id : user
}

Extend type user{
     Id: external
}
```

Is the translation from database to graphql or graphql to database is correct?

Am I right we the above design?

Does Each service that need to communicate  to each other will have a reference to the other service database?

Will I have to manually get the user_id from the User service to insert it in the Post service? 
Do I have to create a custom resolver to manage the foreign key from one service to another?

Do you have a demo that works with a database?

Thank you for your answers

**Comment by chinskiy** [comment]
Hello @cyril36  ,

This repository is going to be archived

Further development of graphene-federation will be at https://github.com/graphql-python/graphene-federation
Please address your further pull requests and issues there

Best regards
