### ISSUE TITLE
Unable to define _entities representations directly in the query

### ISSUE THREAD

**Issue by itallmakesense** [preply/graphene-federation#38]
The problem is when you define _entities representations directly in the query, you'll receive the error:
```
query {
    _entities(representations: [{__typename: "File", id: "1"}]) {
        ... on File {
            id
            name
        }
    }
}
```

```
File ".../site-packages/graphene_federation/entity.py", line 34, in resolve_entities
    model = custom_entities[representation["__typename"]]
graphql.error.located_error.GraphQLLocatedError: 'ObjectValue' object is not subscriptable
```

The only way to use it is to define representations in the variables (https://github.com/preply/graphene-federation/blob/master/examples/entities.py)

`ObjectValue` is created from the parsed request by `graphql-core` and the representation looks like this:
```
ObjectValue(fields=[ObjectField(name=Name(value='__typename'), value=StringValue(value='File')), ObjectField(name=Name(value='id'), value=StringValue(value='1'))])
```

**Comment by chinskiy** [comment]
Hello @itallmakesense  ,

This repository is going to be archived

Further development of graphene-federation will be at https://github.com/graphql-python/graphene-federation
Please address your further pull requests and issues there

Best regards
