### ISSUE TITLE
Required Login decorator for graphene federation

### ISSUE THREAD

**Issue by troptop** [preply/graphene-federation#39]
Hi,
I have tried to develop a required_login decorator for graphene federation.
I dont know if it will be useful, or if it is well done (i am not a dev).
But as i developed it for my own need, i am sharing it and maybe someone would be interested about reviewing it, modifying it and improving 

https://github.com/troptop/graphene_federation_required_login

Best regards

**Comment by chinskiy** [comment]
Hello @troptop ,

This repository is going to be archived

Further development of graphene-federation will be at https://github.com/graphql-python/graphene-federation
Please address your further pull requests and issues there

Best regards
