### ISSUE TITLE
proposal: _entities resolver

### ISSUE THREAD

**Issue by mac2000** [preply/graphene-federation#42]
Hello, here is an use case: I as a developer writing yet another service which only purpose is to extend already existing type in federated graph, e.g. my schema is:

```graphql
extend type File @key(fields:"id") {
  id: ID! @external
  myAwesomeField: String
}
```

To test my service I gonna need to query account somehow, so I forced to add "technical" query resolver for this, e.g.:

```graphql
extend type Query {
  _myTemporaryFileResolverForTesting(id: ID!): File
}
```

With that I am able to make queries in graphiql to test my service without being dependant on another services

**Proposal:** instead of writing this technical query resolvers I might and probably should use build in `_entities` resolver which is used by gateway, query will be something like:

```graphql
{
  _entities(representations:[{__typename:"File",id:"1"}]) {
    ... on File {
      id
      name
    }
  }
}
```

But unfortunately it does not work and complains that `'ObjectValue' object is not subscriptable`

So while query is passed from graphiql somehow we are working with ObjectValues rather than expected dictionary like objects which might be workarounded with addition to **entity.py** like:

```py
if type(representation) is ObjectValue:
  dictified = dict()
  for field in representation.fields:
    dictified[field.name.value] = field.value.value
  representation = dictified
```

right before `model = custom_entities[representation["__typename"]]`

This change should be safe because we are not touching behaviour and will make lives easier

![image](https://user-images.githubusercontent.com/88868/87752341-d231e400-c808-11ea-8302-1a47218e234a.png)

PS: it was early morning, meanwhile there  is an workaround, you actually  can call _entities resolver but it must be  in following form

![image](https://user-images.githubusercontent.com/88868/87756408-8cc5e480-c811-11ea-9138-e25c73eedcaa.png)

**Comment by chinskiy** [comment]
Hello @mac2000  ,

This repository is going to be archived

Further development of graphene-federation will be at https://github.com/graphql-python/graphene-federation
Please address your further pull requests and issues there

Best regards
