### ISSUE TITLE
Graphene v3 support

### ISSUE THREAD

**Issue by noelleleigh** [preply/graphene-federation#44]
Is work being done on this package to make it compatible with [Graphene v3](https://github.com/graphql-python/graphene/issues/1127) ([release notes](https://github.com/graphql-python/graphene/wiki/v3-release-notes))? This update brings in a lot of useful bug fixes, and having the entire Graphene ecosystem ready to go when it's released would make a lot of developer lives easier.

I've been working on making the necessary changes myself, and I'm willing to put up a PR with my fixes. Is that something this project would welcome?

**Comment by erebus1** [comment]
Hi @noelleleigh !
We haven't been working on adopting graphene-federation to Graphene v3 yet, but we'll be happy to see your PR and help you 
if needed!

**Comment by noelleleigh** [comment]
@erebus1 Okay! In the mean time, could you look at the existing PRs and issues and do some triage?

**Comment by kevinhuang28** [comment]
@erebus1 Can you take a look at the PR? I would love for this to be merged in.

Thanks

**Comment by chinskiy** [comment]
Hello @noelleleigh  ,

This repository is going to be archived

Further development of graphene-federation will be at https://github.com/graphql-python/graphene-federation
Please address your further pull requests and issues there

Best regards
