### ISSUE TITLE
Library uses global variables so it means that only one schema can be defined at a time

### ISSUE THREAD

**Issue by tcleonard** [preply/graphene-federation#51]
In case you have an app with 2 schemas (typically often done in unit tests), since the list of entity is stored in a global variable the two schemas collide.

Simple test to reproduce it:
```python
from graphene import ObjectType, ID, Field
from graphene_federation import key, build_schema

@key("id")
class User(ObjectType):
     id = ID(required=True)

class UserQuery(ObjectType):
    user = Field(User)

user_schema = build_schema(query=UserQuery)

@key("id")
class Message(ObjectType):
     id = ID(required=True)

class MessageQuery(ObjectType):
    message = Field(Message)

message_schema = build_schema(query=MessageQuery)

print(message_schema)
``` 

returns the following schema print:
```
schema {
  query: Query
}

type Message {
  id: ID!
}

type Query {
  message: Message
  _entities(representations: [_Any]): [_Entity]
  _service: _Service
}

type User {
  id: ID!
}

scalar _Any

union _Entity = User | Message

type _Service {
  sdl: String
}
```
So as you can see it contains User type... which it shouldn't!

**Comment by chinskiy** [comment]
Hello @tcleonard ,

This repository is going to be archived

Further development of graphene-federation will be at https://github.com/graphql-python/graphene-federation
Please address your further pull requests and issues there

Best regards
