### ISSUE TITLE
graphene-federation 1.0.0 does not work with graphene v3.0.0b7

### ISSUE THREAD

**Issue by jenildesai25** [preply/graphene-federation#56]
Currently I am using graphne v3.0.0b7 with graphene-federation 1.0.0. When I try to build project it throws following error

 ```
Because graphene-federation (==0.1.0) depends on graphene (>=2.1.0,<3)
   and my_project depends on graphene (==v3.0.0b7), graphene-federation is forbidden.
  So, because my_project depends on graphene-federation (==0.1.0), version solving failed.

```

I can change version of graphene and fix it but why is this error coming?

**Comment by Arthur264** [comment]
+1

**Comment by ndy40** [comment]
+1

**Comment by voidnologo** [comment]
+1

**Comment by chinskiy** [comment]
Hello folks,

This repository is going to be archived

Further development of graphene-federation will be at https://github.com/graphql-python/graphene-federation
Please address your further pull requests and issues there

Best regards
