### ISSUE TITLE
Add code/release/changelog for 0.2.0 release to Github

### ISSUE THREAD

**Issue by pb-dod** [preply/graphene-federation#78]
There was recently a 0.2.0 release on Jul 13, 2022 in pypi: https://pypi.org/project/graphene-federation/#files

However, I'm having trouble finding the associated release: https://github.com/preply/graphene-federation/releases

I'm also not seeing a 0.2.0 version bump on the master branch: https://github.com/preply/graphene-federation/commits/master

Can you add the code for the 0.2.0 release to the master branch and cut a release for it?

**Comment by SaulTigh** [comment]
hey @pb-dod , thanks for reaching out. you are totally right, gonna update that soon
