### ISSUE TITLE
Support for Apollo Federation 2

### ISSUE THREAD

**Issue by patrick91** [preply/graphene-federation#83]
Hello there! 👋

Is there any plan for supporting Apollo Federation 2? If not, I'm happy to help with that. I've added support to Strawberry GraphQL recently and I'm happy to help here too 😊

The main changes in Federation 2 are the addition of new directives:

- [ ] @link (this is quite important, as it tells Apollo Gateway and Apollo Router that this schema supports fed 2)
- [ ] @shareable
- [ ] @tag
- [ ] @inaccessible
- [ ] @override

**Comment by chinskiy** [comment]
Hello @patrick91 ,

This repository is going to be archived

Further development of graphene-federation will be at https://github.com/graphql-python/graphene-federation
Please address your further pull requests and issues there

Best regards
